import type { Metadata } from 'next';
import Link from 'next/link';
import { createPageMetadata } from '@/lib/seo';
import { IndiaAuthorityNote } from '@/components/india/IndiaAuthorityNote';

export const metadata: Metadata = createPageMetadata({ title: 'Home Loan Interest Rates India (2026): Compare Lenders and EMI Impact', description: 'Compare major Indian home-loan interest rates with EMI impact and borrower-fit guidance.', pathname: '/in/home-loan-interest-rates-india' });

export default function HomeLoanRatesIndiaPage() {
  return (
    <article className="space-y-6"><header className="rounded-2xl border bg-white p-6"><h1 className="text-3xl font-semibold">Home loan interest rates in India: compare lenders using EMI impact, not only lowest headline</h1><p className="mt-2 text-sm">Who this is for: home buyers comparing floating-rate offers and reset clauses.</p></header><section className="rounded-2xl border bg-white p-6 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b"><th className="px-3 py-2 text-left">Lender</th><th className="px-3 py-2 text-left">Starting rate p.a.</th><th className="px-3 py-2 text-left">Processing fee</th><th className="px-3 py-2 text-left">EMI on ₹50,00,000 / 20y</th></tr></thead><tbody><tr className="border-b"><td className="px-3 py-2">SBI</td><td className="px-3 py-2">~8.40%</td><td className="px-3 py-2">Up to 0.35%</td><td className="px-3 py-2">~₹43,200</td></tr><tr className="border-b"><td className="px-3 py-2">HDFC</td><td className="px-3 py-2">~8.50%</td><td className="px-3 py-2">0.50% range</td><td className="px-3 py-2">~₹43,500</td></tr><tr><td className="px-3 py-2">ICICI</td><td className="px-3 py-2">~8.75%</td><td className="px-3 py-2">0.50% range</td><td className="px-3 py-2">~₹44,250</td></tr></tbody></table></section><section className="rounded-2xl border bg-white p-6 text-sm"><p><strong>Biggest mistake to avoid:</strong> comparing only initial rate and ignoring reset frequency and fee stack.</p><p className="mt-2"><strong>Best decision based on scenario:</strong> choose the offer with stable servicing quality and lower total 3-year cost, not only month-1 EMI.</p><div className="mt-3 flex flex-wrap gap-3"><Link href="/in/loans" className="text-blue-700">Loans hub</Link><Link href="/in/real-estate" className="text-blue-700">Real estate hub</Link><Link href="/in/best-credit-cards-india" className="text-blue-700">Credit card alternatives</Link><Link href="/in/calculators/emi-calculator" className="text-blue-700">EMI calculator</Link><Link href="/in/best-savings-accounts-india" className="text-blue-700">Savings comparison</Link></div></section><IndiaAuthorityNote /></article>
  );
}
