import type { Metadata } from 'next';
import Link from 'next/link';
import { createPageMetadata } from '@/lib/seo';
import { IndiaAuthorityNote } from '@/components/india/IndiaAuthorityNote';

export const metadata: Metadata = createPageMetadata({ title: 'Fixed Deposit vs SIP India (2026): Returns, Risk, and Goal Fit', description: 'Compare FD and SIP for Indian investors with real monthly investment scenarios and trade-off tables.', pathname: '/in/fixed-deposit-vs-sip-india' });

export default function FdVsSipIndiaMoneyPage() {
  return (
    <article className="space-y-6"><header className="rounded-2xl border bg-white p-6"><h1 className="text-3xl font-semibold">Fixed Deposit vs SIP in India: which is better for your goal timeline?</h1><p className="mt-2 text-sm">Who this is for: savers deciding between stable returns and long-term growth.</p></header><section className="rounded-2xl border bg-white p-6 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b"><th className="px-3 py-2 text-left">Monthly Invest</th><th className="px-3 py-2 text-left">FD @ 7.0% (10y)</th><th className="px-3 py-2 text-left">SIP @ 12.0% (10y)</th><th className="px-3 py-2 text-left">Decision note</th></tr></thead><tbody><tr className="border-b"><td className="px-3 py-2">₹5,000</td><td className="px-3 py-2">~₹8,60,000</td><td className="px-3 py-2">~₹11,60,000</td><td className="px-3 py-2">Start with SIP only if downturns are tolerable.</td></tr><tr className="border-b"><td className="px-3 py-2">₹20,000</td><td className="px-3 py-2">~₹34,40,000</td><td className="px-3 py-2">~₹46,40,000</td><td className="px-3 py-2">Split strategy often best for near + long goals.</td></tr><tr><td className="px-3 py-2">₹50,000</td><td className="px-3 py-2">~₹86,00,000</td><td className="px-3 py-2">~₹1,16,00,000</td><td className="px-3 py-2">Use risk buckets and rebalancing discipline.</td></tr></tbody></table></section><section className="rounded-2xl border bg-white p-6 text-sm"><p><strong>Biggest mistake to avoid:</strong> putting near-term goal money in volatile SIP assets.</p><p className="mt-2"><strong>Best decision based on scenario:</strong> for 0–3 year goals use FD-heavy; for 7+ year goals use SIP-heavy with emergency reserve in place.</p><div className="mt-3 flex flex-wrap gap-3"><Link href="/in/investing" className="text-blue-700">Investing hub</Link><Link href="/in/banking" className="text-blue-700">Banking hub</Link><Link href="/in/best-investment-apps-india" className="text-blue-700">Investment apps</Link><Link href="/in/calculators/sip-calculator" className="text-blue-700">SIP calculator</Link><Link href="/in/best-savings-accounts-india" className="text-blue-700">Savings comparison</Link></div></section><IndiaAuthorityNote /></article>
  );
}
