'use client';

import { useMemo } from 'react';
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from 'recharts';
import { usePreferences } from '@/components/providers/PreferenceProvider';
import { ChartKind, ProjectionPoint } from '@/lib/calculators/types';

const COLORS = ['#06b6d4', '#6366f1', '#f59e0b', '#ef4444'];

type ChartCopy = {
  title: string;
  helperText: string;
};

const CHART_COPY: Record<ChartKind, ChartCopy> = {
  growth: {
    title: 'Projected portfolio value',
    helperText: 'Tracks how your balance can grow each year from contributions and returns.'
  },
  amortization: {
    title: 'Remaining balance over time',
    helperText: 'Shows how your outstanding balance is expected to reduce year after year.'
  },
  pie: {
    title: 'Where your final balance comes from',
    helperText: 'Compares your own contributions with the amount generated by growth.'
  },
  bar: {
    title: 'Milestone balance checkpoints',
    helperText: 'Highlights key points in your timeline so progress is easy to compare.'
  }
};

export function ProjectionChart({ chartKind, projection }: { chartKind: ChartKind; projection: ProjectionPoint[] }) {
  const { formatCurrency, darkMode } = usePreferences();

  const stepSize = useMemo(() => {
    if (projection.length <= 10) return 1;
    return Math.ceil(projection.length / 10);
  }, [projection.length]);

  const chartData = useMemo(
    () => projection.filter((_, index) => index % stepSize === 0 || index === projection.length - 1),
    [projection, stepSize]
  );

  const latest = projection.at(-1);
  const pieData = [
    { name: 'Contributions', value: Math.max(0, latest?.contributed ?? 0) },
    { name: 'Growth', value: Math.max(0, latest ? latest.balance - latest.contributed : 0) }
  ];

  const formatCurrencyValue = (value: number) => formatCurrency(Math.round(value));

  const formatAxisCurrency = (value: number) => {
    if (Math.abs(value) >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
    if (Math.abs(value) >= 1_000) return `${(value / 1_000).toFixed(0)}K`;
    return `${Math.round(value)}`;
  };

  const axisColor = darkMode ? '#cbd5e1' : '#334155';
  const gridColor = darkMode ? '#334155' : '#e2e8f0';
  const tooltipStyle = darkMode
    ? { borderRadius: 10, borderColor: '#475569', backgroundColor: '#0f172a', color: '#e2e8f0' }
    : { borderRadius: 10, borderColor: '#cbd5e1', backgroundColor: '#ffffff', color: '#0f172a' };

  if (!projection.length) {
    return (
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <p className="text-sm font-medium text-slate-700 dark:text-slate-200">No projection data available yet.</p>
        <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Adjust your inputs to generate a chart.</p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900">
      <div className="mb-3">
        <h3 className="text-sm font-semibold text-slate-900 dark:text-white">{CHART_COPY[chartKind].title}</h3>
        <p className="text-xs text-slate-600 dark:text-slate-300">{CHART_COPY[chartKind].helperText}</p>
      </div>

      <div className="h-64">
        <ResponsiveContainer width="100%" height="100%">
          {chartKind === 'growth' ? (
            <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 4, bottom: 0 }}>
              <defs>
                <linearGradient id="growthGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#06b6d4" stopOpacity={0.8} />
                  <stop offset="95%" stopColor="#06b6d4" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
              <XAxis dataKey="year" tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} tickMargin={8} />
              <YAxis tickFormatter={formatAxisCurrency} tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} width={50} />
              <Tooltip
                formatter={(value: number) => formatCurrencyValue(value)}
                labelFormatter={(label) => `Year ${label}`}
                contentStyle={tooltipStyle}
              />
              <Area name="Balance" dataKey="balance" stroke="#0891b2" fill="url(#growthGradient)" strokeWidth={2} />
              <Legend />
            </AreaChart>
          ) : chartKind === 'amortization' ? (
            <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 4, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
              <XAxis dataKey="year" tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} tickMargin={8} />
              <YAxis tickFormatter={formatAxisCurrency} tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} width={50} />
              <Tooltip
                formatter={(value: number) => formatCurrencyValue(value)}
                labelFormatter={(label) => `Year ${label}`}
                contentStyle={tooltipStyle}
              />
              <Area name="Remaining balance" dataKey="balance" stroke="#4f46e5" fill="#818cf8" fillOpacity={0.2} strokeWidth={2} />
              <Legend />
            </AreaChart>
          ) : chartKind === 'pie' ? (
            <PieChart>
              <Tooltip formatter={(value: number) => formatCurrencyValue(value)} contentStyle={tooltipStyle} />
              <Legend verticalAlign="bottom" height={36} />
              <Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="46%" outerRadius={88}>
                {pieData.map((entry, index) => (
                  <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
            </PieChart>
          ) : (
            <BarChart data={chartData} margin={{ top: 10, right: 10, left: 4, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
              <XAxis dataKey="year" tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} tickMargin={8} />
              <YAxis tickFormatter={formatAxisCurrency} tick={{ fontSize: 12, fill: axisColor }} stroke={axisColor} width={50} />
              <Tooltip
                formatter={(value: number) => formatCurrencyValue(value)}
                labelFormatter={(label) => `Year ${label}`}
                contentStyle={tooltipStyle}
              />
              <Legend />
              <Bar name="Balance" dataKey="balance" fill="#14b8a6" radius={[6, 6, 0, 0]} />
            </BarChart>
          )}
        </ResponsiveContainer>
      </div>
    </div>
  );
}
