import { buildInvestmentProjection, currencyBreakdown } from '@/lib/calculators/engine';
import { BaseCalculatorInputs, CalculatorResult } from '@/lib/calculators/types';

export const calculateCompoundInterest = (inputs: BaseCalculatorInputs): CalculatorResult => {
  const projection = buildInvestmentProjection(inputs);
  const futureValue = projection.at(-1)?.balance ?? inputs.loanAmount;
  const totalContributions = inputs.loanAmount + inputs.monthlyContribution * inputs.years * 12;
  const interestEarned = futureValue - totalContributions;

  return {
    title: 'Compound Growth Projection',
    summary: [
      { label: 'Future Value', value: futureValue, currency: true, helpText: 'Portfolio balance at the end of the selected period.' },
      { label: 'Interest Earned', value: interestEarned, currency: true, helpText: 'Growth generated by compounding, excluding contributions.' },
      { label: 'Total Contributions', value: totalContributions, currency: true, helpText: 'Total principal contributed over the projection period.' }
    ],
    projection,
    breakdown: [
      currencyBreakdown('Starting Balance', inputs.loanAmount),
      currencyBreakdown('Monthly Contribution', inputs.monthlyContribution),
      { label: 'Expected Return', value: `${inputs.expectedReturn}%` }
    ],
    chartKinds: ['growth', 'pie']
  };
};
