import type { Metadata } from 'next';
import Link from 'next/link';
import { createPageMetadata } from '@/lib/seo';
import { IndiaAuthorityNote } from '@/components/india/IndiaAuthorityNote';

export const metadata: Metadata = createPageMetadata({ title: 'Best Credit Cards India (2026): Fees, Rewards, and User-Type Fit', description: 'Compare top Indian credit cards with annual fee, reward rate, and waiver rules by user profile.', pathname: '/in/best-credit-cards-india' });

export default function BestCardsIndiaPage() {
  return (
    <article className="space-y-6"><header className="rounded-2xl border bg-white p-6"><h1 className="text-3xl font-semibold">Best credit cards in India (2026): choose by spend pattern, not welcome bonus</h1><p className="mt-2 text-sm">Who this is for: salaried users deciding first rewards card or optimizing existing portfolio.</p></header><section className="rounded-2xl border bg-white p-6 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b"><th className="px-3 py-2 text-left">Card</th><th className="px-3 py-2 text-left">Joining/Annual fee</th><th className="px-3 py-2 text-left">Reward potential</th><th className="px-3 py-2 text-left">Good for</th></tr></thead><tbody><tr className="border-b"><td className="px-3 py-2">HDFC Millennia</td><td className="px-3 py-2">₹1,000/₹1,000</td><td className="px-3 py-2">Up to 5% on selected merchants</td><td className="px-3 py-2">Online spenders</td></tr><tr className="border-b"><td className="px-3 py-2">SBI Cashback Card</td><td className="px-3 py-2">₹999/₹999</td><td className="px-3 py-2">5% online cashback (caps apply)</td><td className="px-3 py-2">Simple cashback users</td></tr><tr><td className="px-3 py-2">ICICI Amazon Pay</td><td className="px-3 py-2">₹0/₹0</td><td className="px-3 py-2">Amazon-heavy cashback</td><td className="px-3 py-2">No-fee seekers</td></tr></tbody></table></section><section className="rounded-2xl border bg-white p-6 text-sm"><p><strong>Biggest mistake to avoid:</strong> paying annual fee without crossing spend waiver threshold.</p><p className="mt-2"><strong>Best decision based on scenario:</strong> if annual spend is below ₹2,00,000, zero-fee card usually beats premium reward cards.</p><div className="mt-3 flex flex-wrap gap-3"><Link href="/in/banking" className="text-blue-700">Banking hub</Link><Link href="/in/best-savings-accounts-india" className="text-blue-700">Savings accounts</Link><Link href="/in/best-investment-apps-india" className="text-blue-700">Investment apps</Link><Link href="/in/calculators/emi-calculator" className="text-blue-700">EMI calculator</Link><Link href="/in/home-loan-interest-rates-india" className="text-blue-700">Loan comparison page</Link></div></section><IndiaAuthorityNote /></article>
  );
}
